// Assign any Dimensioned Scalars for input values or field initialisation
dimensionedScalar	sigma_e(transportProperties.lookup("sigma_e"));
dimensionedScalar	sigma_p(transportProperties.lookup("sigma_p"));
dimensionedScalar	source_term(transportProperties.lookup("source_term"));
dimensionedScalar	tor_x(transportProperties.lookup("tor_x"));
dimensionedScalar	tor_y(transportProperties.lookup("tor_y"));
dimensionedScalar	tor_z(transportProperties.lookup("tor_z"));
