#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory
#cd $PWD || exit 1
set -ue
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo
echo -e "\e[1;34m---------- Setting up the case files ----------\e[0m"
echo

# Test if directory location is valid
if [[ ! -d $PWD/constant || ! -d $PWD/system ]]
	then
	{
		echo "Current Path is not a valid case file"
		echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
		echo
	   	exit 1;
	}
	else
	{
		if [[ $PWD != *run* ]]
		then
		{
			echo "Current case directory is not within $FOAM_RUN"
			echo
		echo -e "\e[1;34m----------     ::ERROR::     ----------\e[0m"
			echo
	   		exit 1;
		}
		fi
	}
fi

# Create the mesh
echo "Creating the mesh:"
runApplication blockMesh
echo
# Create topological multi-domain addressing
echo "Creating the topological multi-domain addressing:"
runApplication topoSet
echo
# Create the divided and addressed mesh
echo "Creating the divided multi-domain mesh:"
runApplication splitMeshRegions -cellZones -overwrite
echo
# Apply the boundary Conditons
echo "Applying the boundary conditions and initial field values for:"
while read line
do
	echo -ne $line " "
	for i in $line
	do
		changeDictionary -region $i > log.changeDictionary.$i 2>&1
	done
done <regions.list
# inform user that the process is complete
echo
echo
echo -e "\e[1;34m---------- Case setup complete ----------\e[0m"
echo
ls -C --color=auto *
echo
# ----------------------------------------------------------------- end-of-file
