// Assign any Dimensioned Scalars for input values or field initialisation
dimensionedScalar	sigma_e(transportProperties.lookup("sigma_e"));
dimensionedScalar	sigma_p(transportProperties.lookup("sigma_p"));
dimensionedScalar	source_termBV(transportProperties.lookup("source_termBV"));
dimensionedScalar	source_termTHV(transportProperties.lookup("source_termTHV"));
dimensionedScalar	tor_x(transportProperties.lookup("tor_x"));
dimensionedScalar	tor_y(transportProperties.lookup("tor_y"));
dimensionedScalar	tor_z(transportProperties.lookup("tor_z"));

